#!/bin/bash

# Variables
DAEMON="/your-pocketmine-server-directory/"
USER="your-username"

# Constants
SCRIPT="start.sh"
LOG_FILE="daemon.log"

get_the_pid()
{
    THEPID=$(ps -u arik | grep php | awk '{print $1}')
    PID=0
    [[ $THEPID =~ ^[-0-9]+$ ]] && PID=$THEPID
}

do_start()
{
    printf "Starting PocketMine... "
    get_the_pid
    if [ $PID  -ne 0 ] ; then
        echo "[ ALREADY RUNNING ]"
        RETVAL=1
    else
        runuser -l "$USER" -c "$DAEMON$SCRIPT >> $DAEMON$LOG_FILE &" && echo "[ OK ]"
        RETVAL=$?
    fi
}

do_stop()
{
    printf "Stopping PocketMine... "
    get_the_pid
    while [ $PID -ne 0 ]; do
        if [ $PID -ne 0 ]; then
            kill -9 $PID
        fi
        get_the_pid
    done
    echo "[ OK ]"
    RETVAL=$?
}

do_status()
{
    printf "PocketMine is... "
    get_the_pid
    if [ $PID -ne 0 ]; then
        echo "[ RUNNING ]"
    else
        echo "[ NOT RUNNING ]"
    fi
    RETVAL=1
}

case "$1" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
                sleep 1
                do_start
                ;;
        status)
                do_status
                ;;
        *)
                echo "Usage: $0 {start|stop|restart|status}"
                RETVAL=1
esac
exit $RETVAL
